### ISSUE TITLE
While dev box is booting displays better error if trying to interact with it

### ISSUE THREAD

**Issue by eduardolundgren** [wedeploy/cli#23]
Currently the behavior when dev box is booting is to respond EOF when other CLI commands are executed, e.g.

```
~/P/l/demo-wechat ❯❯❯ we projects                                                                                                     ⏎ master
Get http://localhost:8080/projects: EOF
exit status 1
```

Would be ideal to show a more descriptive error: `Launchpad is booting, hang tight.` Or something like this.

**Comment by henvic** [comment]
Please see a workaround I do for the run command here: https://github.com/launchpad-project/cli/blob/de8ea5c3f57f0cdd09f9c5aeb905af7a78f2e167/run/run.go#L194-L213

I might reuse this code to infer if Launchpad is on or not, but it would be more robust if I relied on a proper health-checking endpoint. If it is robust enough I might even not throw an error, but instead add a delay window (say, 10s) for the execution of the command.

What about a /system/status health-check endpoint for the Launchpad service?

When everything is ready, response might be:
```json
{
    "status": "on"
}
```

Other values such as "since", "current_time", "environment", etc might be useful.

**Comment by henvic** [comment]
This command window would work like this:
Say, Launchpad is getting up and user types "launchpad projects"

He immediately sees "Launchpad is booting, hang tight. %ds".
Where %d is a countdown number from, say, 10 to 0 (seconds).

If Launchpad is up within this window, the countdown message is erased and the command continues to run. Otherwise, the program terminates.

**Comment by cirocosta** [comment]
Hey guys, i was toying around with an idea, check this out: https://github.com/cirocosta/docker-playground/tree/master/availability

It consists of having a file that contains signals the health of the server (`UP` or `DOWN`). Such file is then exposed through TCP via `socat`. 

![out3](https://cloud.githubusercontent.com/assets/3574444/15269115/6534928e-19cb-11e6-8676-f287bf27a24c.gif)

wdyt?

**Comment by henvic** [comment]
I was planning to providing status info over udp on "launchpad run" so that
other local (as in localhost) commands would use it before running the
commands (because I don't want to verify over HTTP all times on every
command due to a number of reasons, such as complexity).

This health-check udp/tcp service being on the server-side (with more info)
should do it.

**Comment by henvic** [comment]
Closing with d211482c026881e8fcd87789dfd2a88bd0ed18df.
